---
title: "Untitled"
author: "Niken"
date: "11/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny) 
library(dplyr) 
library(ggplot2) 
library(plotly) 
library(tidyverse)
library(tm)
tokped_data<- read.csv("dataset_review_tokped_labelled.csv") 


TextDoc <- Corpus(VectorSource(tokped_data$Review))
TextDoc_dtm <- TermDocumentMatrix(TextDoc)
dtm_m <- as.matrix(TextDoc_dtm)
dtm_v <- sort(rowSums(dtm_m),decreasing=TRUE)
dtm_d <- data.frame(word = names(dtm_v),freq=dtm_v)
```

```{r}
ui <- fluidPage(titlePanel("Visualisasi Label Berdasarkan Review User"),
               sidebarLayout(
                 sidebarPanel(
                   actionButton("positif","Visualisasi data bernilai Positif"),
                   actionButton("neutral","Visualisasi data bernilai Netral"),
                   actionButton("negatif", "Visualisasi data bernilai Negatif"),
                   actionButton("all", "Visualisasi data Keseluruh"),
                   actionButton("top", "Visualisasi Kata yang sering muncul")
                 ),
                
                 mainPanel(
                   plotlyOutput(outputId = "aq_plot")
                 )
     )
)
```

```{r server}
server <- function(input, output, session) {
                 observeEvent( input$positif,{
                  result <- tokped_data %>%
                    group_by(Sentiment) %>% filter(Sentiment == "positive") %>%
                    summarise(jumlah = length(Sentiment)) %>%
                    ggplot(aes(x=Sentiment, y=jumlah)) + geom_col() + 
  labs(x = "Label Positif", 
                                                                                        y = "Jumlah Review", 
                                                                                        title = "Grafik Label Positif", 
                                                                                        subtitle = "Visualisasi berdasarkan review bernilai positif")
                   output$aq_plot<-renderPlotly(result)
                 })
                 observeEvent( input$neutral,{
                   result <- tokped_data %>%
                    group_by(Sentiment) %>% filter(Sentiment == "neutral") %>%
                    summarise(jumlah = length(Sentiment)) %>%
                    ggplot(aes(x=Sentiment, y=jumlah)) + geom_col() + 
  labs(x = "Label Netral", 
                                                                                        y = "Jumlah Review", 
                                                                                        title = "Grafik Label Netral", 
                                                                                        subtitle = "Visualisasi berdasarkan review bernilai netral")
                   output$aq_plot<-renderPlotly(result)
                 })
                 observeEvent( input$negatif, { 
                   result <- tokped_data %>%
                     group_by(Sentiment) %>%
                    filter(Sentiment == "negative") %>% 
                    summarise(jumlah = length(Sentiment)) %>%
                    ggplot(aes(x=Sentiment, y=jumlah)) + geom_col() + 
labs(x = "Label Negatif", 
                                                                                        y = "Jumlah Review", 
                                                                                        title = "Grafik Label Negatif", 
                                                                                        subtitle = "Visualisasi berdasarkan review bernilai negatif")
                   output$aq_plot<-renderPlotly(result)
                 })
                 observeEvent( input$all, { 
                   result <- tokped_data %>%
                     group_by(Sentiment) %>%
                    summarise(jumlah = length(Sentiment)) %>%
                    ggplot(aes(x=Sentiment,y = jumlah)) + geom_col()
labs(x = "Label Keseluruhan", 
                                                                                        y = "Jumlah Review", 
                                                                                        title = "Grafik Label Keseluruhan", 
                                                                                        subtitle = "Perbandingan Label dari review seluruh pengguna")
                   output$aq_plot<-renderPlotly(result)
                 })
                 observeEvent( input$top,{
                  top = head(dtm_d)
                  result <- top %>% ggplot(aes(x=word, y=freq)) + geom_col() +coord_flip() + labs(x = "Kata",
                                                                                       y = "Frekuensi",
                                                                                       title = "Grafik kemunculan kata-kata",
                                                                                       subtitle = "Kata kata dengan kemunculan paling banyak")
                   output$aq_plot<-renderPlotly(result)
                 })
}
```

```{r run-app}
shinyApp(ui = ui, server = server, options = list(height = "700px"))
```